### ISSUE TITLE
Combine.py does nothing?

### ISSUE THREAD

**Issue by oaeigfiuhaei** [mystiqality/PiRapGenerator#2]
D:\PiRapGenerator-main\output>py Combine.py
Traceback (most recent call last):
  File "D:\PiRapGenerator-main\output\Combine.py", line 22, in <module>
    sortedList = sorted(wavList, key = lambda x: int(x.split("Rap")[1]))
  File "D:\PiRapGenerator-main\output\Combine.py", line 22, in <lambda>
    sortedList = sorted(wavList, key = lambda x: int(x.split("Rap")[1]))
IndexError: list index out of range

This always pops up no matter what I type or when.

**Comment by mystiqality** [comment]
oh whoops. .  not sure what i did there but what does your directory look like at the moment. are the WAVs 20 digits long or 1000 digits long?

**Comment by mystiqality** [comment]
*20k digits or 1k digits

**Comment by mystiqality** [comment]
Actually never mind, I can't find the file I originally got that snippet from, or where it came from in the first place. If you really want it to work you could replace line 22 with "sortedList = natsorted(wavList)" after installing & importing that module

**Comment by oaeigfiuhaei** [comment]
Each of my WAVs are 1,000 digits, and it goes up to 10,000,000. I tried your suggestion and it didnt work, but "sortedList = sorted(wavList)" did work, however it only combines 2 files at a time and sorts it alphabetically, so like <1000000, 100000, 10000, 1000, 1100000... etc>

**Comment by mystiqality** [comment]
I just ran it using natsorted and it worked perfectly. could you send a screenshot of the code+shell of it not working with natsorted?

**Comment by oaeigfiuhaei** [comment]
![image](https://user-images.githubusercontent.com/114777591/193414387-6aae76ff-7aec-4454-9539-9591544461b4.png)
![image](https://user-images.githubusercontent.com/114777591/193414408-c8911b47-f6ce-4750-88f6-0a26ab73c287.png)

**Comment by mystiqality** [comment]
Most likely you haven't installed and imported the module. If you have pip installed and added to PATH, run 'pip install natsort' in cmd, then add 'from natsort import natsorted' to the top of combine.py

**Comment by oaeigfiuhaei** [comment]
I'm back after finishing another 10m digit run (this time the audios were exactly the same length by the sample), it works, thank you!
